### ISSUE TITLE
example directory missing

### ISSUE THREAD

**Issue by clivez** [nokia/danm#11]
A demo about Multi-domain service discovery is mentioned in the README, but the example directory does not exist in current project, will someone please upload the related files into the project? Thank you.

**Comment by Levovar** [comment]
yep, it is definitely on me to provide these! 

Unfortunately I didn't have much time recently to finish the README, but nevertheless it is in my backlog. I will try and work out the example manifest for the scenario described in the README within week, let's say

In case I'm late feel free to nag me more about it :)
