### ISSUE TITLE
"kubectl get all" should list danmnet resources

### ISSUE THREAD

**Issue by lzcmoody** [nokia/danm#112]
**Is this a BUG REPORT or FEATURE REQUEST?**:  
FEATURE REQUEST

> Uncomment only one, leave it on its own line:
>
>
> feature

**What happened**: 
"kubectl get all " command cannot list danmnet resource.

**What you expected to happen**: 
"kubectl get all" should list danmnet resource.

**How to reproduce it**: 
inevitable

**Anything else we need to know?**: 
add "categories: - all" to danmnet crd could fix this issue.
![image](https://user-images.githubusercontent.com/10054949/61921733-b5b1f180-af90-11e9-8651-121da31b66c7.png)

**Environment**: nokia NCIR19 FP1/OE19 Server.
- danm version: v3.3.0
- Kubernetes version (use `kubectl version`): v1.15.0
- danm configuration: not needed
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
good idea, and why not? :)

will do
