### ISSUE TITLE
DANM IP is not released from the pool (danmeps) when a pod restarts

### ISSUE THREAD

**Issue by fm9282** [nokia/danm#113]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> bug
> feature

**What happened**:
Config 2 IPs in the allocation pool, and 2 Pods up and running.
When one Pod restarts, the new Pod gets stuck in ‘ContainerCreating’ state and the old Pod has terminated successfully. But the DANM IP is not released.
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- danm version 3.2.0
- Kubernetes version (use `kubectl version`): v1.13.4
- danm configuration:
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Kernel (e.g. `uname -a`):5.0.2-1.el7.elrepo.x86_64
- Others:

**Comment by Levovar** [comment]
we don't really support older versions, or maintain maintenance branches.
Have you tried the same scenario with DANM 4.0? There were corrections in the IPAM area which came after 3.2, so I suggest upgrading your cluster first to the latest version, and then re-try

**Comment by Levovar** [comment]
@fm9282 any update?

**Comment by Levovar** [comment]
based on silence I extrapolate that you did not discover a new issue, just observed an older one :)
but if not, feel free to re-open!
