### ISSUE TITLE
Does sriov have to be type:DanmNet?

### ISSUE THREAD

**Issue by hymgg** [nokia/danm#126]
Modified device_plugin_demo for my env.

$ cat sriov_ns.yaml
kind: Namespace
apiVersion: v1
metadata: 
  name: example-sriov
  labels:
    name: example-sriov

$ cat sriov_net.yaml
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: sriov-a
spec:
  NetworkID: sriov-a
  NetworkType: sriov
  Options:
    device_pool: "intel.com/sriov_net_A"
    container_prefix: data_net
    rt_tables: 250
    cidr: 10.200.20.0/24
    allocation_pool:
      start: 10.200.20.10
      end: 10.200.20.100

$ kubectl get cn -n example-sriov
NAME      AGE
default   5d5h
sriov-a   14m
$ kubectl get dn -n example-sriov
No resources found.
$ kubectl get tn -n example-sriov
No resources found.

$ cat sriov_pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod
  namespace: example-sriov
  labels:
    env: test
  annotations:
    danm.k8s.io/interfaces: |
      [
        {"network":"sriov-a", "ip":"dynamic"}
      ]
spec:
  containers:
  - name: sriov-pod
    image: busybox:latest
    args:
      - sleep
      - "1000"
    resources:
      requests:
        intel.com/sriov_net_A: '1'
      limits:
        intel.com/sriov_net_A: '1'
  nodeSelector:
    sriov: enabled

Events:
  Type     Reason                  Age                From                        Message
  ----     ------                  ----               ----                        -------
  Normal   Scheduled               20s                default-scheduler           Successfully assigned example-sriov/sriov-pod to mtx-huawei2-bld04
  Warning  FailedCreatePodSandBox  19s                kubelet, mtx-huawei2-bld04  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9786535d3a11138932aef19bd8a33dd2049a1fb837cfd6ea933a79293521cc43" network for pod "sriov-pod": NetworkPlugin cni failed to set up pod "sriov-pod_example-sriov" network: CNI network could not be set up: CNI operation for network: failed with:failed to get network object for Pod:sriov-pod's connection no.:0 due to:requested network:sriov-a of type:DanmNet in namespace:example-sriov does not exist

Thanks.  -Jessica

**Comment by Levovar** [comment]
with new APIs came new ways to connect to them :)
Please check the updated network attach schema, particularly:
https://github.com/nokia/danm/blob/master/schema/network_attach.yaml#L31

**Comment by hymgg** [comment]
@Levovar Thank you, pod is running with clusterNetwork.

$ cat sriov_pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod
  namespace: example-sriov
  labels:
    env: test
  annotations:
    danm.k8s.io/interfaces: |
      [
        {"clusterNetwork":"default", "ip":"dynamic"},
        {"clusterNetwork":"sriov-a", "ip":"dynamic"}
      ]
spec:
  containers:
  - name: sriov-pod
    image: busybox:latest
    args:
      - sleep
      - "1000"
    resources:
      requests:
        intel.com/sriov_net_A: '1'
      limits:
        intel.com/sriov_net_A: '1'
  nodeSelector:
    sriov: enabled

Here're the networks:

$ cat calico-mgmt.yaml
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: default
spec:
  NetworkID: calico-mgmt
  NetworkType: calico


$ cat sriov_net.yaml
apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: sriov-a
spec:
  NetworkID: sriov-a
  NetworkType: sriov
  Options:
    device_pool: "intel.com/sriov_net_A"
    container_prefix: data_net
    rt_tables: 250
    cidr: 10.200.20.0/24
    allocation_pool:
      start: 10.200.20.10
      end: 10.200.20.100


Now I have 3 such pods,

pod0 running on node 1
  eth0: 10.100.2.152
  data_net1: 10.200.20.10

pod1 running on node 1
  eth0: 10.100.2.153
  data_net1: 10.200.20.11

pod2 running on node 2
  eth0: 10.100.9.64
  data_net1: 10.200.20.12

The 3 can ping each other on eth0, 

pod0 can ping pod1 on data_net1, can't ping pod2 though.

What do I need to add / enable so the 3 could ping each other on data_net1?


$ kubectl -n example-sriov exec sriov-pod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if65: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
    link/ether 62:ee:51:ac:ba:61 brd ff:ff:ff:ff:ff:ff
    inet 10.100.2.152/32 scope global eth0
       valid_lft forever preferred_lft forever
59: data_net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 58:f9:87:78:cd:ab brd ff:ff:ff:ff:ff:ff
    inet 10.200.20.10/24 brd 10.200.20.255 scope global data_net1
       valid_lft forever preferred_lft forever


$ kubectl -n example-sriov exec sriov-pod1 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if66: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
    link/ether e2:61:b0:f8:c5:91 brd ff:ff:ff:ff:ff:ff
    inet 10.100.2.153/32 scope global eth0
       valid_lft forever preferred_lft forever
57: data_net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 58:f9:87:78:cd:a9 brd ff:ff:ff:ff:ff:ff
    inet 10.200.20.11/24 brd 10.200.20.255 scope global data_net1
       valid_lft forever preferred_lft forever


$ kubectl -n example-sriov exec sriov-pod2 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if66: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
    link/ether fe:ee:a8:9f:5b:5c brd ff:ff:ff:ff:ff:ff
    inet 10.100.9.64/32 scope global eth0
       valid_lft forever preferred_lft forever
61: data_net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 58:f9:87:78:cd:cd brd ff:ff:ff:ff:ff:ff
    inet 10.200.20.12/24 brd 10.200.20.255 scope global data_net1
       valid_lft forever preferred_lft forever


Thanks.   -Jessica

**Comment by Levovar** [comment]
well you have basically created a flat L3 network on your hosts, so if you want connectivity, you need to configure your switch
i.e. create a VLAN in your switch, configure it for your ports, add the VLAN tag in the ClusterNetwork

**Comment by hymgg** [comment]
Thank you @Levovar. Worked after adding vlan id to cn.

Is it possible to have multiple entries for vlan, e.g. 
vlan: 100, 200
if 100 and 200 are L3 route-able in ToR switching?

**Comment by Levo-var** [comment]
Not at the moment. We consider 1 VLAN to be one network, at least that's the usual cabling and switch setup I'm used to
Is there any reason behind using multiple tags to mark effectively the same network?

**Comment by hymgg** [comment]
The 2 networks were intended to be separate, reachable only within the local chassis. Then there was a need to connect them so routing was added. Changing vlan tags on switches and nodes require some labor ;o)

Not a blocking issue, just would be nice to have that flexibility.

Thanks.  -Jessica

**Comment by Levo-var** [comment]
The timing here is that regardless how much we labor and workaround, networks are still not resources in K8s.
Which means the required network connections if a Pod are not taken into account when K8s makes scheduling decisions.
One side goal of DANM 4.0 was that it provides me a basis of changing this (that will be th holy grail of networking :)), but we are not there yet

Until that unfortunetaly networking in K8s requires uniform network setup on all hosts. If your setup is not homogenous, I advise creating quasi "availability zones" within your cluster with Node labels.
Create different networks with the different VLANs, and direct the scheduling of your Pods connecting to these networks with  labels

**Comment by hymgg** [comment]
Understood.

quasi "availability zones" with Node labels -- that's kinda what I'm doing. 

Thanks.  -Jessica
