### ISSUE TITLE
IP address out of the range of allocation pool can be used when using static IP

### ISSUE THREAD

**Issue by clivez** [nokia/danm#128]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
bug
> feature

**What happened**:
In the defination of danmnet we have
```
    cidr: 192.168.15.0/24
    allocation_pool:
      start: 192.168.15.10
      end: 192.168.15.60
```
While requesting a static IP out of the range
```
      annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network":"test-net",
              "ip": "192.168.15.80/24"
            }
          ]
```
The pod can still get the IP
```
[root@clive-alp-control-01 case]# kubectl get pods -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP              NODE                  NOMINATED NODE   READINESS GATES
busybox-6594b4998b-qjcpn   1/1     Running   0          3s    192.168.15.80   clive-alp-worker-02   <none>           <none>
```

**What you expected to happen**:
DANM should return an error when the requested static IP is out of the range of allocation pool

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- danm version
- Kubernetes version (use `kubectl version`):
- danm configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
well, whether DANM should return an error is actually not a given.
the behaviour is while a little bit under documented, is actually right now the intended!

think about when would you use static IPs. basically the only reason to use them is for rigid TelCo stuff who connect to external network entities.
now, when these gateways use static IPs they actually become unscalable. it means they either run, or not, there is no standby component to take its place (well, there is, but usually it also has another static IP)
arguably these kind of components should enjoy priority over those which are okay with dynamic IPs. however, if we would constrict static IPs to the allocation pool, a dynamic component could actually take its "slot"
which results in a static component, without backup to fail forever. while in a reverse situation: the dynamic component could simply take the next free address, no issue

so actually allocation pool is the tool with which you can make sure dynamic and static components connecting to the same network do not clash.
simply validating static IPs against the same pool is a backward incompatible change from this perspective

**Comment by clivez** [comment]
ok, got it, I will close this issue.
