### ISSUE TITLE
How to verify and use services created by svcwatcher on 2nd networks

### ISSUE THREAD

**Issue by hymgg** [nokia/danm#133]
Hello,

Looking into svcwatcher.

Created a few pods using 2 networks, default is calico, 2nd is sriov

$ cat sriov_pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod
  namespace: example-sriov
  labels:
    env: test
  annotations:
    danm.k8s.io/interfaces: |
      [
        {"clusterNetwork":"default", "ip":"dynamic"},
        {"clusterNetwork":"sriov-a", "ip":"dynamic"}
      ]
spec:
  containers:
  - name: sriov-pod
    image: busybox:latest
    args:
      - sleep
      - "1000"
    resources:
      requests:
        intel.com/sriov_net_A: '1'
      limits:
        intel.com/sriov_net_A: '1'
  nodeSelector:
    sriov: enabled

Created a headless service on calico in usual k8s way, spec.selector is used to find pods.

$ cat calico_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: calico-service
  namespace: example-sriov
spec:
  clusterIP: None
  selector:
    env: test
  ports:
  - name: zeromq
    port: 5555
    protocol: TCP

Created a headless service on sriov in danm way, metadata.annotations is used to find pods.

$ cat sriov_svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sriov-service
  namespace: example-sriov
  annotations:
    danm.k8s.io/selector: '{"env":"test"}'
    danm.k8s.io/network: sriov-a
spec:
  clusterIP: None
  ports:
  - name: zeromq
    port: 5555
    protocol: TCP

Found endpoints from calico-service, but not sriov-service

$ kubectl get ep calico-service -n example-sriov
NAME             ENDPOINTS                                                           AGE
calico-service   10.100.11.173:5555,10.100.2.154:5555,10.100.3.86:5555 + 3 more...   4d

$ kubectl get ep sriov-service -n example-sriov
NAME            ENDPOINTS   AGE
sriov-service   <none>      4d21h

From sriov-pod, can't even resolve service kubernetes.default

$ kubectl -n example-sriov exec sriov-pod -- nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

command terminated with exit code 1

$ kubectl -n example-sriov exec sriov-pod -- cat /etc/resolv.conf
nameserver 10.96.0.10
search example-sriov.svc.cluster.local svc.cluster.local cluster.local dc1.xxx.com. corp.xxx.com.
options ndots:5

Tried another pod, the svcwatcher pod, 
can resolve kubernetes.default, calico-service.example-sriov.svc.cluster.local, 
can not resolve sriov-service.example-sriov.svc.cluster.local, sriov-pod.example-sriov.pod.cluster.local

$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup kubernetes.default
nslookup: can't resolve '(null)': Name does not resolve

Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local

$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup calico-service.example-sriov.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      calico-service.example-sriov.svc.cluster.local
Address 1: 10.100.2.154 10-100-2-154.calico-service.example-sriov.svc.cluster.local
Address 2: 10.100.3.87 10-100-3-87.calico-service.example-sriov.svc.cluster.local
Address 3: 10.100.9.65 10-100-9-65.calico-service.example-sriov.svc.cluster.local
Address 4: 10.100.11.173 10-100-11-173.calico-service.example-sriov.svc.cluster.local
Address 5: 10.100.3.86 10-100-3-86.calico-service.example-sriov.svc.cluster.local
Address 6: 10.100.7.75 10-100-7-75.calico-service.example-sriov.svc.cluster.local

$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup sriov-service.example-sriov.svc.cluster.local

nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'sriov-service.example-sriov.svc.cluster.local': Name does not resolve
command terminated with exit code 1

$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup sriov-pod.example-sriov.pod.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'sriov-pod.example-sriov.pod.cluster.local': Name does not resolve
command terminated with exit code 1

How do we reference / connect to these pods / services on secondary networks, besides using pod IPs? Is there some kind of DNS names for pods / services on secondary networks?

Thanks.  -Jessica

**Comment by Levo-var** [comment]
Similarly to network connections, the new APIs also resulted in new explicit ways of connecting them to Services
Kindly check the Services schem descriptor, but hint:
    danm.k8s.io/clusterNetwork: ## NETWORK_SELECTOR ##

Whether you can actually resolve a Service is dependant on your cluster setup, not on DANM. 
If you have network connectivity to cluster DNS from your Pod, and your Service has Endpoints they should behave as usual. 
DANM only provisions the endpoints, nothing else

**Comment by hymgg** [comment]
Thank you for the hint, that was a stupid mistake, my brain was somewhere else when I blindly copy&pasted from example.

Now the sriov-service has endpoints

$ kubectl get ep sriov-service -n example-sriov
NAME            ENDPOINTS                                               AGE
sriov-service   10.200.20.10:5555,10.200.20.11:5555,10.200.20.12:5555   6d20h


The DNS resolution is still a bit of mystery here.

The svcwatcher from kube-system and sriov-pod3 from example-sriov have the same default clusterNetwork.

From svcwatcher pod, DNS resolution works, not from sriov-pod3.


$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup kubernetes.default

Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

$ kubectl -n example-sriov exec sriov-pod3 -- nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

command terminated with exit code 1

$ kubectl -n kube-system exec svcwatcher-z5p55 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if84: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue state UP 
    link/ether 72:37:a2:a9:61:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.68/32 scope global eth0
       valid_lft forever preferred_lft forever

$ kubectl -n example-sriov exec sriov-pod3 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if85: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
    link/ether 26:f8:14:8d:d1:21 brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.69/32 scope global eth0
       valid_lft forever preferred_lft forever

$ kubectl -n kube-system exec svcwatcher-z5p55 -- ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 

$ kubectl -n example-sriov exec sriov-pod3 -- ip route
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link

$ kubectl -n kube-system exec svcwatcher-z5p55 -- cat /etc/resolv.conf
nameserver 10.96.0.10
search kube-system.svc.cluster.local svc.cluster.local cluster.local dc1.xxx.com. corp.xxx.com.
options ndots:5

$ kubectl -n example-sriov exec sriov-pod3 -- cat /etc/resolv.conf
nameserver 10.96.0.10
search example-sriov.svc.cluster.local svc.cluster.local cluster.local dc1.xxx.com. corp.xxx.com.
options ndots:5

$ kubectl -n example-sriov exec sriov-pod3 -- ping 10.100.0.68
PING 10.100.0.68 (10.100.0.68): 56 data bytes
64 bytes from 10.100.0.68: seq=0 ttl=63 time=0.082 ms
64 bytes from 10.100.0.68: seq=1 ttl=63 time=0.054 ms

**Comment by hymgg** [comment]
Just looking for differences between the 2 pods.

$ kubectl -n kube-system exec svcwatcher-z5p55 -- env|grep SERVICE_HOST
KUBE_DNS_SERVICE_HOST=10.96.0.10
KUBERNETES_DASHBOARD_SERVICE_HOST=10.104.149.4
KUBERNETES_SERVICE_HOST=10.96.0.1
DANM_WEBHOOK_SVC_SERVICE_HOST=10.96.248.40
CALICO_TYPHA_SERVICE_HOST=10.98.210.254

$ kubectl -n example-sriov exec sriov-pod3 -- env|grep SERVICE_HOST
KUBERNETES_SERVICE_HOST=10.96.0.1

**Comment by Levo-var** [comment]
I'm afraid that is something Calico related
This env variables do not come from DANM AFAIK
Can't it be that Calico has some default deny network policy active for pods in some namespaces?

**Comment by hymgg** [comment]
You're right, starting pod in kube-system gives more env variables. Doesn't help DNS resolution though.

$ kubectl -n kube-system exec sriov-pod3 -- env|grep SERVICE_HOST
KUBERNETES_SERVICE_HOST=10.96.0.1
CALICO_TYPHA_SERVICE_HOST=10.98.210.254
KUBERNETES_DASHBOARD_SERVICE_HOST=10.104.149.4
KUBE_DNS_SERVICE_HOST=10.96.0.10
DANM_WEBHOOK_SVC_SERVICE_HOST=10.96.248.40

$ kubectl -n kube-system exec svcwatcher-z5p55 -- env|grep SERVICE_HOST
KUBE_DNS_SERVICE_HOST=10.96.0.10
KUBERNETES_DASHBOARD_SERVICE_HOST=10.104.149.4
KUBERNETES_SERVICE_HOST=10.96.0.1
DANM_WEBHOOK_SVC_SERVICE_HOST=10.96.248.40
CALICO_TYPHA_SERVICE_HOST=10.98.210.254

$ kubectl -n kube-system exec sriov-pod3 -- nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

command terminated with exit code 1

$ kubectl -n kube-system exec svcwatcher-z5p55 -- nslookup kubernetes.default

nslookup: can't resolve '(null)': Name does not resolve
Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local

$ kubectl -n kube-system exec sriov-pod3 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if88: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue 
    link/ether d6:08:b9:8b:3e:81 brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.72/32 scope global eth0
       valid_lft forever preferred_lft forever


$ kubectl -n kube-system exec svcwatcher-z5p55 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if84: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue state UP 
    link/ether 72:37:a2:a9:61:a1 brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.68/32 scope global eth0
       valid_lft forever preferred_lft forever

$ kubectl -n kube-system exec svcwatcher-z5p55 -- ip r
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 

$ kubectl -n kube-system exec sriov-pod3 -- ip r
default via 169.254.1.1 dev eth0 
169.254.1.1 dev eth0 scope link 


===
The only difference I can tell, is svcwatcher pod eth0 has "state UP", same with webhook pod, but not the sriov-pod3... Is there something I need to add to sriov-pod3's definition?


$ kubectl -n kube-system exec danm-webhook-deployment-84dd5c4894-dh8jx -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if68: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue state UP 
    link/ether 6e:2c:34:8b:e1:8e brd ff:ff:ff:ff:ff:ff
    inet 10.100.8.35/32 scope global eth0
       valid_lft forever preferred_lft forever

$ kubectl -n kube-system exec sriov-pod3 -- ping 10.100.8.35
PING 10.100.8.35 (10.100.8.35): 56 data bytes
64 bytes from 10.100.8.35: seq=0 ttl=62 time=0.232 ms
64 bytes from 10.100.8.35: seq=1 ttl=62 time=0.141 ms


$ cat sriov_pod3.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod3
  namespace: kube-system
  labels:
    env: test
spec:
  containers:
  - name: sriov-pod3
    image: busybox:latest
    args:
      - sleep
      - "1000"

**Comment by hymgg** [comment]
$ kubectl describe service kube-dns -n kube-system
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=KubeDNS
Annotations:       prometheus.io/port: 9153
                   prometheus.io/scrape: true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP:                10.96.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         10.100.11.171:53,10.100.7.74:53
Port:              dns-tcp  53/TCP
TargetPort:        53/TCP
Endpoints:         10.100.11.171:53,10.100.7.74:53
Port:              metrics  9153/TCP
TargetPort:        9153/TCP
Endpoints:         10.100.11.171:9153,10.100.7.74:9153
Session Affinity:  None
Events:            <none>


$ kubectl -n kube-system exec sriov-pod3 -- ping 10.100.11.171
PING 10.100.11.171 (10.100.11.171): 56 data bytes
64 bytes from 10.100.11.171: seq=0 ttl=62 time=0.174 ms
64 bytes from 10.100.11.171: seq=1 ttl=62 time=0.100 ms
^C


$ kubectl -n kube-system exec sriov-pod3 -- ping 10.100.7.74
PING 10.100.7.74 (10.100.7.74): 56 data bytes
64 bytes from 10.100.7.74: seq=0 ttl=62 time=0.200 ms
64 bytes from 10.100.7.74: seq=1 ttl=62 time=0.117 ms
^C

**Comment by hymgg** [comment]
replaced busybox with alpine. DNS resolution worked ;o)

$ cat sriov_pod3.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sriov-pod3
  namespace: kube-system
  annotations:
  labels:
    env: test
spec:
  containers:
  - name: sriov-pod3
    image: alpine:latest
    args:
      - sleep
      - "1000"


$ kubectl -n kube-system exec sriov-pod3 -- nslookup kubernetes.default

Name:      kubernetes.default
Address 1: 10.96.0.1 kubernetes.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

$ kubectl -n kube-system exec sriov-pod3 -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if90: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1440 qdisc noqueue state UP 
    link/ether 4e:00:33:1e:d9:3a brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.74/32 scope global eth0
       valid_lft forever preferred_lft forever

**Comment by hymgg** [comment]
the ip a output led to a suspicion that busybox might be too primitive, somehow.

Will see how it goes with container images from our apps.
