### ISSUE TITLE
New installation problem

### ISSUE THREAD

**Issue by belvarr** [nokia/danm#152]
**perhaps BUG**:

 bug

**What happened**:
New installation give me this error for master release : 
# go get -d github.com/nokia/danm
package github.com/nokia/danm: no Go files in /root/go/src/github.com/nokia/danm

**Environment**:
- danm version : master
- go version: go version go1.13 linux/amd64 
after that i have tried to run ./build_danm.sh but it hangs on 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz

please any help ?

**Comment by Levovar** [comment]
well, that's not really an error actually :)

it just says there is no source files located directly in the project's root to be compiled, which is the expected considering we follow the example golang project outline

the hanging is basically due to the upstream servers getting overloaded, which happens quite frequently around CEST 2-4pm according to my experience. I guess this is when the US folks wake up
I think the only thing you can do is retry, and hope the servers can handle your request

**Comment by belvarr** [comment]
I can confirm that i have build the binaries last week but now I face this error 

Step 7/8 : RUN apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*
 ---> Running in c4cb15113a00
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz


WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz


WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz: network error (check Internet connection and firewall)
ERROR: unsatisfiable constraints:
  ca-certificates (missing):
    required by: world[ca-certificates]
The command '/bin/sh -c apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*' returned a non-zero code: 1
build_danm.sh error on line : 9 command was: docker

Also there is no internet problem as i can fetch the file APKINDEX.tar.gz successfully from host

Thank you

**Comment by belvarr** [comment]
I found the problem that I have installed my k8s cluster via kubespray which installed docker with no internet access for new default containers as I have searched for that and fix it:

https://github.com/kubernetes-sigs/kubespray/issues/2002

I don't know if they had changed any thing during last period which causing the failure as I didn't face this problem before.

Thanks for your support.

**Comment by elgamal2020** [comment]
Hello ,

I have the same problem , I tired to implement the WA but I got the same issue 

ubuntu@node11:~/go/src/github.com/nokia/danm$ sudo iptables -t nat -A POSTROUTING -s 172.17.0.0/16 ! -d 10.0.0.0/8 -m addrtype ! --dst-type LOCAL -j MASQUERADE
ubuntu@node11:~/go/src/github.com/nokia/danm$ sudo ./build_danm.sh
Updating alpine base image
latest: Pulling from library/alpine
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest
Building DANM builder container
Sending build context to Docker daemon  4.608kB
Step 1/8 : FROM alpine:latest
 ---> e7d92cdc71fe
Step 2/8 : MAINTAINER Levente Kale <levente.kale@nokia.com>
 ---> Running in 0a917db5b8b1
Removing intermediate container 0a917db5b8b1
 ---> 88de9afa16d3
Step 3/8 : ENV GOPATH=/usr/local/go
 ---> Running in 7c58fe074a31
Removing intermediate container 7c58fe074a31
 ---> 3aa87292ab3e
Step 4/8 : ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
 ---> Running in 8e68cd2f07f2
Removing intermediate container 8e68cd2f07f2
 ---> dc733f482b9a
Step 5/8 : ENV GO_VERSION 1.12.9
 ---> Running in e5f8c8e04027
Removing intermediate container e5f8c8e04027
 ---> 2eb08551853a
Step 6/8 : COPY build.sh /build.sh
 ---> bb42ab45126c
Step 7/8 : RUN apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*
 ---> Running in f544a648382b
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  ca-certificates (missing):
    required by: world[ca-certificates]
The command '/bin/sh -c apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*' returned a non-zero code: 1
build_danm.sh error on line : 9 command was: docker
Terminating with error!

**Comment by elgamal2020** [comment]
@Levovar Please re-open it 

Thanks a lot

Best Regards

**Comment by Levovar** [comment]
@elgamal2020 the script runs without issues in my environment
I suspect the upstream Alpine repo was simpy temporarily out when you tried to build. please try again, hopefully it succeeds

**Comment by BurlyLuo** [comment]
@Levovar  In order to try this comment,but the person always meet the problem.Ithink the step is build the image for the comment.why not directly release the image in the DANM‘s github page of the special version. we can release many version for DANM in the github,and the person can easily get the image.many country can  not access the alpine's repo,or cat not build the image.
so would you mind release the image in the github page?

**Comment by BurlyLuo** [comment]
Many contry that they can not access the website,so they can not build the image.
INFO]  --> Fetching gopkg.in/inf.v0
[INFO]  --> Fetching gopkg.in/yaml.v2
[WARN]  Unable to checkout github.com/ghodss/yaml
[ERROR] Update failed for github.com/ghodss/yaml: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-ghodss-yaml'...
fatal: unable to access 'https://github.com/ghodss/yaml/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/api
[WARN]  Unable to checkout github.com/gogo/protobuf
[ERROR] Update failed for github.com/gogo/protobuf: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-gogo-protobuf'...
fatal: unable to access 'https://github.com/gogo/protobuf/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/apimachinery
[WARN]  Unable to checkout github.com/gregjones/httpcache
[ERROR] Update failed for github.com/gregjones/httpcache: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-gregjones-httpcache'...
fatal: unable to access 'https://github.com/gregjones/httpcache/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/client-go
[WARN]  Unable to checkout github.com/apparentlymart/go-cidr
[ERROR] Update failed for github.com/apparentlymart/go-cidr: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-apparentlymart-go-cidr'...
fatal: unable to access 'https://github.com/apparentlymart/go-cidr/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/klog
[WARN]  Unable to checkout github.com/modern-go/concurrent
[ERROR] Update failed for github.com/modern-go/concurrent: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-modern-go-concurrent'...
fatal: unable to access 'https://github.com/modern-go/concurrent/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/kube-openapi
[WARN]  Unable to checkout github.com/golang/groupcache
[ERROR] Update failed for github.com/golang/groupcache: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-golang-groupcache'...
fatal: unable to access 'https://github.com/golang/groupcache/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[INFO]  --> Fetching k8s.io/kubernetes
[WARN]  Unable to checkout github.com/imdario/mergo
[ERROR] Update failed for github.com/imdario/mergo: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-imdario-mergo'...
fatal: unable to access 'https://github.com/imdario/mergo/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[WARN]  Unable to checkout github.com/google/gofuzz
[ERROR] Update failed for github.com/google/gofuzz: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-google-gofuzz'...
fatal: unable to access 'https://github.com/google/gofuzz/': Failed to connect to github.com port 443: Connection refused
: exit status 128
[WARN]  Unable to checkout golang.org/x/crypto
[ERROR] Update failed for golang.org/x/crypto: Cannot detect VCS

**Comment by Levovar** [comment]
the reason of not releasing the image is unfortunetaly a legal one, not a technical.
I myself would also very much like to be able to release ready-made Docker images, believe me :)

@CsatariGergely can explain the blockers

**Comment by BurlyLuo** [comment]
Unfortunately.

**Comment by elgamal2020** [comment]
I think the problem I am facing is quite different and related to ceritifcates as I can fetch the images as seen below 

Any WA , alternative way ? 


*** System restart required ***
Last login: Fri Feb 28 04:17:58 2020 from 10.0.1.3
ubuntu@node11:~$ sudo apt update^C
ubuntu@node11:~$ cd /go/src/github.com/nokia/danm
-bash: cd: /go/src/github.com/nokia/danm: No such file or directory
ubuntu@node11:~$ cd go/src/github.com/nokia/danm
ubuntu@node11:~/go/src/github.com/nokia/danm$  sudo ./build_danm.sh
Updating alpine base image
latest: Pulling from library/alpine
Digest: sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest
Building DANM builder container
Sending build context to Docker daemon  4.608kB
Step 1/8 : FROM alpine:latest
 ---> e7d92cdc71fe
Step 2/8 : MAINTAINER Levente Kale <levente.kale@nokia.com>
 ---> Running in 2e5c63bc03b5
Removing intermediate container 2e5c63bc03b5
 ---> fabaacdc7546
Step 3/8 : ENV GOPATH=/usr/local/go
 ---> Running in 2d744a622996
Removing intermediate container 2d744a622996
 ---> cb39a6914e50
Step 4/8 : ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
 ---> Running in c9c30f1bfd6c
Removing intermediate container c9c30f1bfd6c
 ---> a5c96d48494b
Step 5/8 : ENV GO_VERSION 1.12.9
 ---> Running in 8290a00b6700
Removing intermediate container 8290a00b6700
 ---> bf97ace2dca3
Step 6/8 : COPY build.sh /build.sh
 ---> 18b05fdc92fd
Step 7/8 : RUN apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*
 ---> Running in 7d0eb88cc06e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  ca-certificates (missing):
    required by: world[ca-certificates]
The command '/bin/sh -c apk add --no-cache ca-certificates  && apk update --no-cache  && apk upgrade --no-cache  && apk add --no-cache make gcc musl-dev glide git bash curl tar  && mkdir -p ${GOPATH}  && mkdir -p ${GOPATH}/bin  && mkdir -p ${GOPATH}/src  && curl -fsSL -k https://dl.google.com/go/go${GO_VERSION}.src.tar.gz | tar zx --strip-components=1 -C ${GOPATH}  && cd ${GOPATH}/src/  && ./make.bash  && rm -rf /var/cache/apk/*  && rm -rf /var/lib/apt/lists/*  && rm -rf /tmp/*' returned a non-zero code: 1
build_danm.sh error on line : 9 command was: docker
Terminating with error!
ubuntu@node11:~/go/src/github.com/nokia/danm$

**Comment by elgamal2020** [comment]
Could you please help for that ?

**Comment by BurlyLuo** [comment]
@elgamal2020 https://www.katacoda.com/courses/kubernetes/playground
Maybe  you could use this website to build the image,and then push them to the docker hub ,you can get the image from your own docker hub.
pls  have a try.about the binary,you can put them to  a  jumper .

**Comment by Levovar** [comment]
yeah the scripts should be usable from any public CI pipelines. the same is running in Travis CI without any issues
if they don't work in your private environmnet that is an environment specific issue
