### ISSUE TITLE
Restriction of length of the danmnet name should not be applied to the danmnets that do not use vxlan/vlan

### ISSUE THREAD

**Issue by clivez** [nokia/danm#163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 bug
> feature

**What happened**:
Danmnets (for external network, no vxlan/vlan used) with long names can work in old version of DANM, but after the upgrade of DANM, these danmnets could no longer work because of the restriction of name length.

**What you expected to happen**:
I think we will need to identify whether a danmnet uses vxlan/vlan or not when checking, if not, the restriction of name length is not needed.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
ok +1, this can be done
welcome any PRs :)
