### ISSUE TITLE
IP leak after nodes reboot

### ISSUE THREAD

**Issue by clivez** [nokia/danm#167]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 bug
> feature

**What happened**:
One of the pods in the cluster requires fix IP, it worked normally at the beginning, but after the reboot of the nodes, it could not come up again because "requested fix ip address is already in use".
From the log recorded by DANM, a DEL operation was performed without any error, but the 'Alloc' field was not updated accordingly.
Seems the problem may come from the code below:
https://github.com/nokia/danm/blob/v4.0.0/pkg/metacni/metacni.go#L568-L571
DANM will not return error if there is any problem when releasing the IP in danmnet.

**What you expected to happen**:
Need to add some operations when DANM fails to release IP address in danmnet.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
CNIs should not return errors happening during CNI_DEL to Kubelet because your Pod will get stuck in infinite termination loop
also DANM does clear the IPs upon CNI_DEL being invoked. in the reboot case the problem is that CNI_DEL is not invoked by Kubelet after it comes back online, at all

you state it did happen, which is contrary to our experience. can you provide evidence for this claim?

**Comment by clivez** [comment]
```
[root@cwe2 ~]# kubectl describe danmnet -ncompaas cfx2019
Name:         cfx2019
Namespace:    compaas
Labels:       <none>
Annotations:  <none>
API Version:  danm.k8s.io/v1
Kind:         DanmNet
Metadata:
  Creation Timestamp:  2019-11-26T04:51:10Z
  Generation:          4
  Resource Version:    4621965
  Self Link:           /apis/danm.k8s.io/v1/namespaces/compaas/danmnets/cfx2019
  UID:                 5d7cff38-1008-11ea-a43f-00fd45f68650
Spec:
  Network ID:    cfx2019
  Network Type:  ipvlan
  Options:
    Alloc:  gAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAE=
    Allocation Pool:
      End:             10.41.137.254
      Start:           10.41.137.101
    Cidr:              10.41.137.101/24
    Container Prefix:  eth1
    Host Device:       eno2
    Rt Tables:         100
Events:                <none>
[root@cwe2 ~]#
```
This is the danmnet we get after the issue happend. You can see the 'Generation' is 4. And this danmnet is used only by 'ci-cmserver-cmserver' pod.
From the timestamp, we know it is created at 2019-11-26 04:51:10, so Generation = 1 then.
From the DANM log:
```
2019/11/26 10:22:52 CNI ADD invoked with: ns:compaas PID:ci-cmserver-cmserver-6595c6db67-nmnfw CID: d55f5bab96b2e97e03309ddac7780b0ef01721b16d91aecbf500429d948981a7
```
==> Generation = 2 here
```
2019/11/26 16:40:31 CNI DEL invoked with: ns:compaas PID:ci-cmserver-cmserver-6595c6db67-nmnfw CID: d55f5bab96b2e97e03309ddac7780b0ef01721b16d91aecbf500429d948981a7
```
==> Generation = 3 here
```
2019/11/26 16:45:04 CNI ADD invoked with: ns:compaas PID:ci-cmserver-cmserver-6595c6db67-75fjs CID: fb0218457b96604ba2877edece1a6bd1ce6afd7110b476ef0b1bfc65e7bb07e1
```
==> Generation = 4 here
Nodes of the cluster rebooted at around 2019/11/26 17:00, then
```
2019/11/26 17:03:43 CNI DEL invoked with: ns:compaas PID:ci-cmserver-cmserver-6595c6db67-75fjs CID: fb0218457b96604ba2877edece1a6bd1ce6afd7110b476ef0b1bfc65e7bb07e1
```
==> Generation should be modified to 5 if danmnet was updated successfully at that time, but unfortunalely not.
And after that, every time when adding we will see error
```
2019/11/26 17:03:53 CNI ADD invoked with: ns:compaas PID:ci-cmserver-cmserver-6595c6db67-75fjs CID: e1dacadc8c3bfde5bc529d2bd12056e071bf90ba6d0ca33e98d2a42abaf9513d
2019/11/26 17:03:54 ERROR: ADD: CNI network could not be set up with error:CNI operation for network:cfx2019 failed with:IP address reservation failed for network:cfx2019 with error:failed to allocate IP address for network:cfx2019 with error:requested fix ip address is already in use
```
No danmep for ci-cmserver-cmserver pod was left in etcd, so on the second DEL call, danmep was deleted but danmnet was not updated successfully.

I understand CNIs should not return errors, but I think DANM maybe need to add some aduit mechanism to make sure the 'Alloc' field in danmnet always in correct state.

**Comment by Levovar** [comment]
could you instrument the code a little to find out why DanmNet update did not happen in Gen4?
or share the full log
if CNI_DEL is invoked, I don't see how it is possible for the CNI component to delete the EP without releasing the IP

**Comment by Levovar** [comment]
@clivez any news?
