### ISSUE TITLE
IP leak when CNI_DEL is not invoked by kubelet

### ISSUE THREAD

**Issue by clivez** [nokia/danm#171]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 bug
> feature

**What happened**:
In some cases, for example node reboot or pause container deleted by docker, CNI_DEL may not invoked by kubelet, as a result, the IP addresses allocated from the danmnets may leak.

**What you expected to happen**:
Need DANM to add some IPAM audit mechanism to check the IP addresses managed by DANM and release them when necessary.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
will be handled by https://github.com/nokia/danm-utils/pull/1

**Comment by Levovar** [comment]
first version of Cleaner utility is developed, tested, and merged. Users worrying about the scenarios mentioned in the Issue should give it a go!
