### ISSUE TITLE
Enhance Fortville + DPDK support by adding extra information on the dummy kernel interface

### ISSUE THREAD

**Issue by Levovar** [nokia/danm#175]
When an application uses a device not managed by the kernel, DANM creates a dummy kernel interface in its place to communicate CaaS allocations to the application.
This was implemented in: https://github.com/nokia/danm/pull/155
However currently we only convey IP address, and IP routes.

The support should be expanded to cover:
- VLAN tag
- SR-IOV PCI address
as well.

Both are possible with a little trickery. the end result could look something like this:
[root@crf-dev ~]# ip -d link show dpdk1
64861: dpdk1@dumdum: <BROADCAST,NOARP,M-DOWN> mtu 1500 qdisc noop state DOWN mode DEFAULT qlen 1000
    link/ether fa:d3:bf:c3:f9:68 brd ff:ff:ff:ff:ff:ff promiscuity 0
    **vlan** protocol 802.1Q id **100** <REORDER_HDR> addrgenmode eui64
    alias **0000:17:03.5**

**Comment by krsna1729** [comment]
Regarding SR-IOV PCI address - 

Is this to disambiguate which DPDK interface is which network interface? Related to discussion here https://github.com/intel/sriov-cni/issues/37 by setting the MAC address of the virtual device same as the VF, we were able to figure out the PCI/DPDK port id related to the network interface. [bess example](https://github.com/omec-project/upf-epc/blob/5be38e28052778994a2580890fe43df7acbf7b24/conf/spgwu.bess#L136-L144)

**Comment by Levovar** [comment]
@krsna1729 that sounds like a great idea, thank you for the pointer and the examples!

**Comment by krsna1729** [comment]
Do both, i.e, add the alias too. Its handy so that we dont have to scan and attach to all dpdk ports, instead explicitly attach the right PCI.

Setting the MAC will help for use-case i mentioned in the other issue where kernel will craft responses and DPDK app sends it out.

**Comment by Levovar** [comment]
@krsna1729 with #214 merged dummy interfaces now look like this, conveying VLAN, PCI ID and even MAC address of the VFIO bound VF.
Let me know if you would like to see anything extra in addition, but otherwise I'll close this ticket :)
# nsenter -t 10885 -n ip -d a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
...
10: net4: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether **9e:cd:49:21:9d:ee** brd ff:ff:ff:ff:ff:ff promiscuity 0
    dummy numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    alias **0000:05:1b.1**
    inet6 fd00:169:254:200::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::9ccd:49ff:fe21:9dee/64 scope link
       valid_lft forever preferred_lft forever

11: a4559c27-b0ce-: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 5a:28:d2:5b:e3:2c brd ff:ff:ff:ff:ff:ff promiscuity 0
    dummy numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    inet6 fe80::5828:d2ff:fe5b:e32c/64 scope link
       valid_lft forever preferred_lft forever

12: net5@a4559c27-b0ce-: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 5a:28:d2:5b:e3:2c brd ff:ff:ff:ff:ff:ff promiscuity 0
    **vlan protocol 802.1Q id 101** <REORDER_HDR> numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
    **alias 0000:05:1a.6**
    inet6 fd00:169:254:200::1/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5828:d2ff:fe5b:e32c/64 scope link
       valid_lft forever preferred_lft forever

# ip link | grep  5a:28:d2:5b:e3:2c
    vf 43 MAC 5a:28:d2:5b:e3:2c, vlan 101, spoof checking on, link-state auto, trust off, query_rss off

[root@bcmt02-host13 ~]# ip link | grep 9e:cd:49:21:9d:ee
    vf 44 MAC 9e:cd:49:21:9d:ee, spoof checking on, link-state auto, trust off, query_rss off
