### ISSUE TITLE
The container build instructions builds un-tagged containers

### ISSUE THREAD

**Issue by uablrek** [nokia/danm#22]
The instruction says;
```
docker build integration/docker/netwatcher
```
But this build set repository and tag to `<none>`. I built both containers and could not see which was which.

I extracted the tag with;
```
grep image: integration/manifests/netwatcher/netwatcher_ds.yaml
```
Then build with;
```
docker build -t library/netwatcher:3.0.0 integration/docker/netwatcher
```
and pushed to a private registry.

**Comment by Levovar** [comment]
Good catch!

Added a -t to the example build command with https://github.com/nokia/danm/commit/c00b8945674e6c44d11c025592a2ea47bb1544e1
