### ISSUE TITLE
vlan binding for default interface of pod  

### ISSUE THREAD

**Issue by sriramec** [nokia/danm#232]
<Support> 

Hi,

Is it possible to define a default management network over a particular vlan, interface like shown below and  have my pod attached to that interface. So that any packets going out of the pod/node are vlan tagged. 

apiVersion: danm.k8s.io/v1
kind: ClusterNetwork
metadata:
  name: defaultvlannw
spec:
  NetworkID: flannel
  NetworkType: flannel
  Options:
     vlan: 901
     host_device: enp59s0f0

One more question is, Is it possible to use "dhcp" plugin under "/opt/cni/bin" with danm. 

We are using the danm packaged in Akraino REC blue print iso from this link. 
https://nexus.akraino.org/content/repositories/images-snapshots/TA/release-1/images/237/

Thanks,
Sriram

**Comment by Levovar** [comment]
feature description for the default network feature can be found here: https://github.com/nokia/danm/blob/master/user-guide.md#defining-default-networks
Note:
- only Pods not defining any network connections are attached to the default automatically
- if a Pod defines any connections, it needs to explicitly define all desired connections
- vlan option is only valid for dynamically supported CNIs, see uer guide again. Flannel does not support vlan tagging

**Comment by Levovar** [comment]
specifically in Akraino REC we create the Flannel overlay over a VLAN so default network is still tagged, but you cannot change it dynamically through DANM cause as I explained above Flannel itsef is not designed like that

**Comment by sriramec** [comment]
Thanks Levovar for your explanation. Since, flannel doesnt support vlan inherently, it is not possible to tag the packets sent through flannel network.  One more question, is it possible use dhcp ipam along with Danm ?

**Comment by Levovar** [comment]
possible with static CNIs, but can't imagine why would you ever do that when DANM already comes with an integrated, all around usable IPAM

**Comment by sriramec** [comment]
Thanks for the reply. I was thinking of a scenario where in the pod additional interface can get the ip address from the dhcp server already running in the site.
