### ISSUE TITLE
Danm does not work with cri-o (or any container runtime except docker)

### ISSUE THREAD

**Issue by uablrek** [nokia/danm#24]
I am using `cri-o` as container runtime and get this error;
```
error:Cannot get container pid!
```
Thacked it down to `getDockerPid()` [here](https://github.com/nokia/danm/blob/c00b8945674e6c44d11c025592a2ea47bb1544e1/pkg/danmep/ep.go#L315).

**Comment by Levovar** [comment]
Project is only compliant with Docker, but not with other runtimes.

**Comment by Levovar** [comment]
Basically it is just a question of using the right Client towards the run-time, but at the moment we only support connecting to a Docker engine, as this is the most popular use-case out there.
Theoretically speaking choosing the right client could be made configurable ofc.

**Comment by uablrek** [comment]
I think you can be "container runtime agnostic" as other CNI plugins seem to be. Copy some code from the main cni plugins. I think I can use delegated CNI's just not the built-in's. My CNI plugin for the main k8s network is "bridge" and works fine.

**Comment by Levovar** [comment]
Yep, we definitely can be! It is just we are not, at the moment.
Basically we are using "docker inspect" to figure out the netns of the infra Pod from its CID, and this is the only reason we have a docker client in the code.
But the same info can be gathered via direct means too, you are  right.

We discussed it internally and @rospring will look into it! Thanks for the find.
Always happy to hear how other people would be / are using the project :)

**Comment by rospring** [comment]
We will correct it soon. netns is coming when cni is invoked.

**Comment by Levovar** [comment]
Fixed with https://github.com/nokia/danm/pull/26

**Comment by uablrek** [comment]
I can confirm that "ipvlan" networks can be created in pods started with `cri-o`.
