### ISSUE TITLE
networkPlugin cni failed to set up pod "danm-installer-mmcqr_kube-system"

### ISSUE THREAD

**Issue by jdambly-ns** [nokia/danm#243]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 bug

**What happened**:
running the installer job fails to run the pod

```
  Warning  FailedCreatePodSandBox  2s (x2 over 5s)    kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "f704fbd4490652949ee8a6aec4b5506a209599e579d25372e31d768c09d1c349" network for pod "danm-installer-gjhkh": networkPlugin cni failed to set up pod "danm-installer-gjhkh_kube-system" network: Pod manifest could not be parsed with error: failed to get Pod info from K8s API server due to:Get https://10.128.128.1:443/api/v1/namespaces/kube-system/pods/danm-installer-gjhkh: x509: certificate signed by unknown authority
```

**What you expected to happen**:
installer job runs to completion 

**How to reproduce it**:
kubctl apply -f integration/install
**Anything else we need to know?**:
I think the issue is in danm-kubeconfig, what creates this kubeconfig?
```
apiVersion: v1
kind: Config
current-context: default
clusters:
  - cluster:
      certificate-authority-data: <<< this is null/missing
```
calico is my default cni
**Environment**:
- DANM version (use `danm -version`): latest (cloned from master)
- Kubernetes version (use `kubectl version`): 1.18.10
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
hi @jdambly-ns! sorry I was on my winter break weren't checking my projects that much
will try to take a look this week and come back to you, but based on first insepction there might some issue with the certificate generating and signing scripts

**Comment by Levovar** [comment]
Looking back at this, I think the installer job's config file is appropriately commented:
https://github.com/nokia/danm/blob/master/integration/install/danm-installer-config.yaml#L29

let us know if you were unable to configure correct CA authority cert for the installer based on the instructions
