### ISSUE TITLE
How to check what is the VF getting assigned to a POD/container while created?

### ISSUE THREAD

**Issue by kanhu** [nokia/danm#258]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> bug
> feature

**What happened**:
i created a container in the virtual envionment. in yaml file requested for a SRIOV Vfs

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:
just need to out of 32 VFs available on the system, which VF is assinged to the container

**Environment**:
- DANM version (use `danm -version`):
- Kubernetes version (use `kubectl version`):
- DANM configuration (K8s manifests, kubeconfig files, CNI config file):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by Levovar** [comment]
DANM is not assigning the VFs, K8s does
see https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources
