### ISSUE TITLE
Support for NodePort service on secondary POD interfaces

### ISSUE THREAD

**Issue by lsoica** [nokia/danm#261]
Hi,

I am trying to setup two k8s clusters where pods are attached on two different networks. One for intra-cluster communication and another one for inter-cluster communication and for accessing the pods from the outside world.

The only option I have for making services externally accessible is through NodePort, like in this diagram:

![image](https://user-images.githubusercontent.com/1623282/134380888-cc714b3d-31bd-4982-a0b2-a76a8d5cc843.png)

The question is, can I have NodePort services on POD interfaces other than default one ?

**Comment by Levovar** [comment]
no
but your assumption that your secondary network interface also needs to be NATted is not true. use IPVLAN/MACVLAN/SR-IOV CNI to **directly** provision the external IP to the secondary interface of your Pod, thus achieving direct connectivity without a need for NAT

**Comment by lsoica** [comment]
Thanks for the confirmation.

The reason behind NodePort requirement is because I only have one IP per k8s node per network. I assume this does not work with IPVLAN/MACVLAN, right ?

**Comment by Levovar** [comment]
no, not really. NATting all your Pod IPs to external NodEIPs is already not best practice TBH

in any case, this has not much to do with DANM so closing the issue
