### ISSUE TITLE
[v4.3.0] - invalid version: module contains a go.mod file, so module path must match major version

### ISSUE THREAD

**Issue by zulh-civo** [nokia/danm#270]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> bug

**What happened**:

I wanted to use the latest [v4.3.0](https://github.com/nokia/danm/releases/tag/v4.3.0) code (specifically, the [clientset types](https://github.com/nokia/danm/tree/v4.3.0/crd/client/clientset/versioned/typed/danm/v1)) in my Go code. But, I ran into some Go mod issues which I believe rooted from upstream/this repo.

I have this import in my Go code:

```go
import (
    danmv1 "github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1"
    // ...
)

// ...
```

When I use `go get github.com/nokia/danm@v4.1.0+incompatible` followed with `go get github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1`, I got:

```
go: module github.com/nokia/danm@upgrade found (v4.1.0+incompatible), but does not contain package github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1
```

I can confirm the clientset types code that I need is [not there](https://github.com/nokia/danm/tree/v4.1.0/crd/client/clientset/versioned/typed/danm/v1) under v4.1.0 tree. But, it's [available](https://github.com/nokia/danm/tree/v4.3.0/crd/client/clientset/versioned/typed/danm/v1) under v4.3.0 tree.

Screenshots:

![Screenshot 2022-06-08 at 2 07 26 PM](https://user-images.githubusercontent.com/75463191/172543857-e853447a-b64e-462c-b01f-7252dd74967b.png)

![Screenshot 2022-06-08 at 2 07 48 PM](https://user-images.githubusercontent.com/75463191/172543873-dfefed75-e31a-44d5-881d-d0d64bb92d38.png)

Not sure if this is related, but I'll highlight it anyways - upon checking [pkg.go.dev website](https://pkg.go.dev/github.com/nokia/danm?tab=versions), I can only see `v4.1.0+incompatible` as latest version. I'm not sure why the v4.3.0 and other versions in between are not showing on that page.

Screenshot:
![Screenshot 2022-06-08 at 2 00 34 PM](https://user-images.githubusercontent.com/75463191/172542896-25ae27b0-ca22-4c1c-853a-92b3f3c036e2.png)

**What you expected to happen**:

- Able to run `go get github.com/nokia/danm@v4.3.0` just fine
- Able to run `go get github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1@v4.3.0` just fine

**How to reproduce it**:

```
$ go get github.com/nokia/danm@v4.3.0
go: github.com/nokia/danm@v4.3.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/nokia/danm/v4")

$ go get github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1@v4.3.0
go: github.com/nokia/danm/crd/client/clientset/versioned/typed/danm/v1@v4.3.0: github.com/nokia/danm@v4.3.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/nokia/danm/v4")
```

**Anything else we need to know?**:

**Environment**:
- DANM version (use `danm -version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DANM configuration (K8s manifests, kubeconfig files, CNI config file): N/A
- OS (e.g. from /etc/os-release): Mac OSX 10.15.7
- Kernel (e.g. `uname -a`): N/A
- Others:
    - Go version
        ```
        go version go1.18.3 darwin/amd64
        ```

**Comment by Levovar** [comment]
heyyo @zulh-civo does the issue still persist or just something was messed up in you local project?

some replies nevertheless!
1: ye the generated code was not part of the repository for a long long time, we just generated it everytime from CI
2: I ultimately decided to include it exactly because I wanted to use it from other repos :) here is an example it's done on our side: https://github.com/nokia/danm-utils/blob/master/go.mod#L7, we use exact commit hash
3: the pkg.go stuff is interesting, no idea about it either. @CsatariGergely you have any clue? did we miss some "release process" stuff?
