### ISSUE TITLE
Add CI for the project

### ISSUE THREAD

**Issue by Kokan** [nokia/danm#3]
There are a few CI you can choose from like Travis.

**Comment by Levovar** [comment]
Actually we already have our Travis workspace, so this is definitely something we are looking into!

I'm planning on integrating at least binary build, and the execution of existing UTs into the system.

No timetables, ofc help is appreciated!

**Comment by Kokan** [comment]
It should be trivial, but I had my issues with the build scripts, around the weekend I think I'll have something to share.
