### ISSUE TITLE
Document the current status of IPv6 support

### ISSUE THREAD

**Issue by navjotsingh83** [nokia/danm#30]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> bug

**What happened**:
Unable to configure a danmnet object with an IPv6 CIDR. If I try with the below yaml 

*apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: ipvlan-danm6
  namespace: default
spec:
  NetworkID: ipvlan-danm6
  NetworkType: ipvlan
  Options:
    host_device: eth0
    cidr: 2a00:8a00:a000:1193:2::e80/122
    allocation_pool:
      start: 2a00:8a00:a000:1193:2::e84
      end: 2a00:8a00:a000:1193:2::e87
    container_prefix: eth0
    rt_tables: 201
    routes:
      ::0/0: 2a00:8a00:a000:1193:2::e81*

Then I get the following error on parsing

_The DanmNet "ipvlan-danm6" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"danm.k8s.io/v1", "kind":"DanmNet", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"danm.k8s.io/v1\",\"kind\":\"DanmNet\",\"metadata\":{\"annotations\":{},\"name\":\"ipvlan-danm6\",\"namespace\":\"default\"},\"spec\":{\"NetworkID\":\"ipvlan-danm6\",\"NetworkType\":\"ipvlan\",\"Options\":{\"allocation_pool\":{\"end\":\"2a00:8a00:a000:1193:2::e87\",\"start\":\"2a00:8a00:a000:1193:2::e84\"},\"cidr\":\"2a00:8a00:a000:1193:2::e80/122\",\"container_prefix\":\"eth0\",\"host_device\":\"eth0\",\"routes\":{\"::0/0\":\"2a00:8a00:a000:1193:2::e81\"},\"rt_tables\":201}}}\n"}, "generation":1, "uid":"783b5c37-f90d-11e8-9437-fa163ebccd59", "selfLink":"", "clusterName":"", "name":"ipvlan-danm6", "namespace":"default", "creationTimestamp":"2018-12-06T04:14:48Z"}, "spec":map[string]interface {}{"NetworkID":"ipvlan-danm6", "NetworkType":"ipvlan", "Options":map[string]interface {}{"allocation_pool":map[string]interface {}{"end":"2a00:8a00:a000:1193:2::e87", "start":"2a00:8a00:a000:1193:2::e84"}, "cidr":"2a00:8a00:a000:1193:2::e80/122", "container_prefix":"eth0", "host_device":"eth0", "routes":map[string]interface {}{"::0/0":"2a00:8a00:a000:1193:2::e81"}, "rt_tables":201}}}: validation failure list:
**spec.Options.cidr in body should match '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))$'**_ 

The last error shows that the cidr supports IPv4 only. This should be corrected.

Actually, I want to use DANM with IPv6 so not sure if this is the only error. I donno if we may need to fix at some more places to support IPv6.

**Environment**:
- danm version 0.3
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- danm configuration:
- OS (e.g. from /etc/os-release): RHEL 7.5 (Maipo)
- Kernel (e.g. `uname -a`): 4.18.16-1.el7.elrepo.x86
- Others:

**Comment by navjotsingh83** [comment]
Hi @Levovar 

Thanks for the update. I tried with net6 and routes6 as you suggested and it worked :). I mean my POD got an IP6 address which I able to ping and do a basic test of service-access from within the cluster. I do not have an IPv6 stack on a node outside the cluster so cannot test external access, but I think it should work. I am even able to configure both IPv4 and IPv6 in single damnet and POD got a dual stack. However I tried only static with IPv6 and not dynamic IP assignment, which I think will not work with IPv6 since the specs do not allow to specify an IPv6 range, correct?

**Comment by Levovar** [comment]
wow, that is actually a better result than I expected :D

Dynamic allocation can also work theoretically, with some restrictions. The 48-bit MAC address, and the the related 64bit EUI are randomly generated, only prefixed with the Net6 CIDR.

Dynamic mode might not work, but feel free to give it a go!

**Comment by Levovar** [comment]
besides re-thinking dynamic IP allocation scheme, Robert tells me some kernel level parameter setting might be also missing from DANM to make this allocation scheme work in all environments

though we currently disagree whose responsibility would be to even set these parameters :)

**Comment by navjotsingh83** [comment]
Hi @Levovar 

I tried with "dynamic" in IPv4 first, it worked. Then I tried with both v4 and v6 as dynamic, i.e.
 _annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network": "ipvlan-danm6",
              "ip": "dynamic",
              "ip6": "dynamic"
            }
          ]_
But I got the error:
NetworkPlugin cni failed to set up pod "compactddesm-6b84d6dc44-p9dnj_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

Also, my point about missing IPv6 ranges in schema is that even if dynamic IPv6 allocation would have worked, we need to specify a pool since the net6 signifies the completer CIDR. All the IPs would not be available in that range so we need to allow ranges like in IPv4, correct?

**Comment by rospring** [comment]
Hi,

eui64 is used with random mac address (not the best way) and prefix defined as net6. I try to check your case with json error.

**Comment by rospring** [comment]
Hi,

if your net6 is:
2a00:8a00:a000:1193:0002:0000:0000:0e80/122

Then our address generation method is not working, i guess. try it with /64 net6 and tell me the result.

thanks!

**Comment by navjotsingh83** [comment]
Hi @rospring,

If I use /64, it works but the POD gets an IP6 address which is not in my provider network (as expected since I have /122).  The POD got the IP : 2a00:8a00:a000:1193:f818:3eff:fe2e:a22

**Comment by Levovar** [comment]
okay, so summarizing the current status:
- we support IPv6
- we support dual-stack
- Resriction1: the minimum subnet size with which IPv6 can be used is /64
- Restriction2: dynamic IP is allocated from the whole CIDR, not possible to specify separate allocation pools

I renamed the Issue  to indicate that this is now more about getting these documented. Keeping it open until documentation happens!

**Comment by nokia-t1zhou** [comment]
> okay, so summarizing the current status:
> 
> * we support IPv6
> * we support dual-stack
> * Resriction1: the minimum subnet size with which IPv6 can be used is /64
> * Restriction2: dynamic IP is allocated from the whole CIDR, not possible to specify separate allocation pools
> 
> I renamed the Issue to indicate that this is now more about getting these documented. Keeping it open until documentation happens!

hi, Levovar, in the new IPAM code, there is a function named ipam.ConfigureIface, it will make sure sysctl "disab le_ipv6" is 0 if we are about to add an IPv6 address to the interface.
but the IPAM which danm used not include such function,  so it will cause that IPv6 address configuration failed in some container which the container image has the init value "1" of net.ipv6.conf.[interface].disable_ipv6.
waiting for your comments.

**Comment by Levovar** [comment]
> > okay, so summarizing the current status:
> > 
> > * we support IPv6
> > * we support dual-stack
> > * Resriction1: the minimum subnet size with which IPv6 can be used is /64
> > * Restriction2: dynamic IP is allocated from the whole CIDR, not possible to specify separate allocation pools
> > 
> > I renamed the Issue to indicate that this is now more about getting these documented. Keeping it open until documentation happens!
> 
> hi, Levovar, in the new IPAM code, there is a function named ipam.ConfigureIface, it will make sure sysctl "disab le_ipv6" is 0 if we are about to add an IPv6 address to the interface.
> but the IPAM which danm used not include such function, so it will cause that IPv6 address configuration failed in some container which the container image has the init value "1" of net.ipv6.conf.[interface].disable_ipv6.
> waiting for your comments.

yep, can confirm :)
we had an internal workshop about the improvements we plan for this year, and yes this is actually a gap we need to address. just forgot to mention the same here on GitHub!
besides setting this parameter within the container's network namespace, we will also set net.ipv6.conf.<DEVICE>.autoconf and net.ipv6.conf.<DEVICE>.auto_ra to value 0, both within, and without of the container namespace

This is also needed to stop the interface from reconfiguring itself!

**Comment by navjotsingh83** [comment]
Hi @Levovar 

I could see these restrictions documented a while back, but unable to find them now. Am I missing something? or are these restrictions removed now?

**Comment by Levovar** [comment]
yep, the restrictions got removed by the PRs linked to this issue:
https://github.com/nokia/danm/issues/147

I1m in the process of qualifying a 4.2 release, and this enhancement is one its major improvement compared to 4.1
