### ISSUE TITLE
Unable to use DANM with calico

### ISSUE THREAD

**Issue by navjotsingh83** [nokia/danm#31]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> bug

**What happened**:
Created a DANMnet object for calico

_Name:         calico-danm
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"danm.k8s.io/v1","kind":"DanmNet","metadata":{"annotations":{},"name":"calico-danm","namespace":"default"},"spec":{"NetworkID":"calico-da...
API Version:  danm.k8s.io/v1
Kind:         DanmNet
Metadata:
  Creation Timestamp:  2018-12-06T12:15:48Z
  Generation:          1
  Resource Version:    1656462
  Self Link:           /apis/danm.k8s.io/v1/namespaces/default/danmnets/calico-danm
  UID:                 aa30e343-f950-11e8-9437-fa163ebccd59
Spec:
  Network ID:    calico-danm
  Network Type:  calico
  Options:
    Allocation _ Pool:
      End:               192.168.1.255
      Start:             192.168.1.2
    Cidr:                192.168.1.0/24
    Container _ Prefix:  eth0
    Host _ Device:       eth0
    Rt _ Tables:         202
  Validation:            True
Events:                  <none>_

Also, created the following calico.conf file in all the nodes in /etc/cnt/net.d path

_{
  "name": "calico-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "mtu": 1500,
      "policy": {
        "type": "k8s"
      },
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv6": "true",
        "assign_ipv4": "true"
      },
      "etcd_endpoints": "https://172.16.1.3:2379",
      "etcd_key_file": "/etc/etcd/ssl/etcd-client-key.pem",
      "etcd_cert_file": "/etc/etcd/ssl/etcd-client.pem",
      "etcd_ca_cert_file": "/etc/etcd/ssl/ca.pem",
      "kubernetes": {
        "kubeconfig": "/etc/kubernetes/cluster-admin.kubeconfig"
      }
    },
    {
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "snat": true
    }
  ]
}_

Now, when use the calico-danm danmnet object in my deployment.yaml as 
      _annotations:
        danm.k8s.io/interfaces: |
          [
            {
              "network": "calico-danm",
              "ip": "192.168.1.3/24"
            }
          ]_

I am getting the error that 
**Error delegating ADD to CNI plugin:calico because:no etcd endpoints specified**

But as you can see in the calico.conf the etcd endpoints are mentioned. Not sure what I am missing.

**Environment**:
- danm version
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- danm configuration:
- OS (e.g. from /etc/os-release): RHEL 7.5
- Kernel (e.g. `uname -a`): 4.18
- Others:

**Comment by rospring** [comment]
Hi,

please try it with plugin config and not with conflist. I.e. extract the calico part from your config and save it as calico.conf.

**Comment by rospring** [comment]
Hi,

I guess calico added default route and you cannot add 2 default gw. Try to use in ipvlan part narrower route than default and tell us the result.

**Comment by navjotsingh83** [comment]
Hi @rospring 

Thanks for the hint. Calico, indeed adds default routes. So I change the routes/routes6 in danmnet config as:
routes:
      **10.0.0.0/8**: 10.53.169.193
routes6:
      **2001:DB8::/32**: 2a00:8a00:a000:1193:2::e81
  
And it worked, I got two interfaces in my POD,

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        **inet 192.168.1.230**  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 2001:db8:1234:0:db66:7925:a570:dfc2  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::5c68:37ff:fe9b:537b  prefixlen 64  scopeid 0x20<link>
        ether 5e:68:37:9b:53:7b  txqueuelen 0  (Ethernet)
        RX packets 10  bytes 1018 (1018.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 1272 (1.2 KiB)
        TX errors 0  dropped 1 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        **inet 10.53.169.228  netmask 255.255.255.192  broadcast 10.53.169.255**
        inet6 fe80::fa16:3e00:12f:b3fc  prefixlen 64  scopeid 0x20<link>
        **inet6 2a00:8a00:a000:1193:2::e84  prefixlen 122  scopeid 0x0<global>**
        ether fa:16:3e:2f:b3:fc  txqueuelen 0  (Ethernet)
        RX packets 31  bytes 1860 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10  bytes 864 (864.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by navjotsingh83** [comment]
@rospring @Levovar 

I tried further by spawning TWO pods with calico and exposing one type of POD behind a service. But I was not able to do service name resolution from the other POD. Further debugging made me realize that the core-dns, heapster, etc. PODs in kube-system were not running owing to the below type of error:

**_NetworkPlugin cni failed to set up pod "coredns-6z45q_kube-system" network: DANM cannot create interfaces for Pod:coredns-6z45q, because no network connections are defined in spec.metadata.annotation_**

I realise that after configuring DANM as the default CNI plugin, the spec for these system objects of K8s also need to specify annotations, correct? Do you see this as a limitation? Does https://github.com/nokia/danm/issues/21 talks about the same problem where the requester has asked for default network?

**Comment by Levovar** [comment]
> I realise that after configuring DANM as the default CNI plugin, the spec for these system objects of K8s also need to specify annotations, correct? Do you see this as a limitation? Does #21 talks about the same problem where the requester has asked for default network?

yes, indeed correct! DANM network creation is opt-in: if you make it your CNI, you need to explicitly define network connections for your Pod

but also yes, we are planning to implement an easy way of centrally setting default networks on a per namespace level!

**Comment by Levovar** [comment]
I will close the issue because I think we have answered all the related queries, and there is no problem related to DANM itself.
Discussion related to the enhancement should be continued in its own thread.
