### ISSUE TITLE
Danm installer and popularization

### ISSUE THREAD

**Issue by libesz** [nokia/danm#35]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Installation is currently a manual procedure, which might include also the compilation of the components.

**What you expected to happen**:
Since the installation steps are not depending on too much decisions or mandatory admin interactions, it could and should be automated similarly to other CNI plugins.

**Draft specs**:
Install and start up all danm components with a single (or maybe a few) `kubectl apply` command. Controller/watcher manifests and RBAC are already available, but the CNI plugin itself has to be distributed also with a DaemonSet+host mounts. I would assume the kubelet is either running natively or if in container, than it has the relevant CNI directories mounted from host.
The installation optionally should cover a default network provisioning for the kube-system namespace in order to allow CoreDNS and other basic addons to work.
The feature depends on #18. The closing task should be to contribute the installation steps to the K8S Kubeadm documentation [here](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) along with the integration to [KubeSpray](https://github.com/kubernetes-sigs/kubespray).

**Comment by Levovar** [comment]
big like, let's make it happen :)

**Comment by BurlyLuo** [comment]
would you mind release a offine-line package to deploy the DANM,it can be let more perople to try this comment。
