### ISSUE TITLE
Failed to list *v1.DanmNet

### ISSUE THREAD

**Issue by adamdembek** [nokia/danm#46]
I have compiled latest danm plugin from github and installed on Kubernetes 1.11 using instruction provided on github. 

The netwatcher started but log error

reflector.go:205] github.com/nokia/danm/pkg/netwatcher/netwatcher.go:22: Failed to list *v1.DanmNet: Get https://10.254.0.1:443/apis/danm.k8s.io/v1/danmnets?limit=500&resourceVersion=0: Gateway Timeout

I see that CustomResourceDefinition returns danmnets.danm.k8s.io but netwatcher tries to use danm.k8s.io/v1/danmnets. Can you confirm if CustomResourceDefinition  should be changed? 

# kubectl get CustomResourceDefinition
NAME                        CREATED AT
brpolices.cbur.bcmt.local   2019-02-12T14:47:04Z
danmeps.danm.k8s.io         2019-02-20T13:44:08Z
danmnets.danm.k8s.io        2019-02-20T13:44:08Z
networks.kubernetes.com     2019-02-12T14:35:27Z

I have created 2 DanmNet in namespace sbc
# kubectl get DanmNet -n sbc
NAME                AGE
trusted-sig-net     1h
untrusted-sig-net   2h

# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"

# uname -a
Linux sbc-loko-483-12-all-in-one-01 4.18.16-1.el7.elrepo.x86_64 #1 SMP Sat Oct 20 12:52:50 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Levovar** [comment]
Nope, that is how it should be. DanmNet is a versioned API

See on my environment, with the same CRD: 
[cloudadmin@controller-1 ~]$ curl --cert /etc/kubernetes/ssl/danm.pem --key /etc/kubernetes/ssl/danm-key.pem  https://10.254.0.1:443/apis/danm.k8s.io/v1/danmnets?limit=500&resourceVersion=0
[1] 1197001
[cloudadmin@controller-1 ~]$ {"apiVersion":"danm.k8s.io/v1","items":[{"apiVersion":"danm.k8s.io/v1","kind":"DanmNet","metadata":{"creationTimestamp":"2019-02-20T13:33:31Z","generation":2,"name":"flannel","namespace":"default","resourceVersion":"23603","selfLink":"/apis/danm.k8s.io/v1/namespaces/default/danmnets/flannel","uid":"1ce7ab1a-3514-11e9-a9e2-a81e843a72bf"},"spec":{"NetworkID":"flannel","NetworkType":"flannel","Options":{"allocation_pool":{"end":"","start":""},"container_prefix":"","host_device":"","rt_tables":0},"Validation":"True"}},{"apiVersion":"danm.k8s.io/v1","kind":"DanmNet","metadata":{"creationTimestamp":"2019-02-20T13:33:54Z","generation":2,"name":"test-net1","namespace":"default","resourceVersion":"23679","selfLink":"/apis/danm.k8s.io/v1/namespaces/default/danmnets/test-net1","uid":"2b0a12be-3514-11e9-a9e2-a81e843a72bf"},"spec":{"NetworkID":"test-net1","NetworkType":"ipvlan","Options":{"allocation_pool":{"end":"","start":""},"container_prefix":"eth0","host_device":"vlan984","rt_tables":201},"Validation":"True"}},
... and so on.
Anyway, the REST client is actually generated by Kubernetes code, so it is really how it should be.

I think you should interpret the returned HTTP error literally: you probably have a connectivity issue to the server.
Can you even reach https://10.254.0.1:443 in your env?

**Comment by adamdembek** [comment]
I do not have danm.pem . 
I tried  /etc/kubernetes/ssl/ca.pem  

curl --cert /etc/kubernetes/ssl/ca.pem --key /etc/kubernetes/ssl/ca-key.pem  https://10.254.0.1:443/apis/danm.k8s.io/v1/danmnets?limit=500&resourceVersion=0

And got 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
  },
  "status": "Failure",
  "message": "danmnets.danm.k8s.io is forbidden: User \"BCMT\" cannot list danmnets.danm.k8s.io at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "danm.k8s.io",
    "kind": "danmnets"
  },
  "code": 403
}

How to generate danm.pem and danm-key.pem ?

**Comment by Levovar** [comment]
I mean obviously use the client cert and key valid within your own environment :)
I have no idea how authentication is set up within the BCMT product, so can't help you there

but 99% something is misconfigured within your specific environment, on the Kubernetes level

either the network connection, or the authentication

**Comment by Levovar** [comment]
gonna close the issue as it is not related to the project itself, but rather, to its integration into a proprietary product

but feel free to come back to us for more info in case something still doesn't work!
