### ISSUE TITLE
go get failing for danm package

### ISSUE THREAD

**Issue by anannaya** [nokia/danm#65]
go get -v github.com/nokia/danm/pkg/ipam
github.com/nokia/danm (download)
# cd /home/anannaya/data/STUDIES/PROGRAMMING/Go_programs/go/src/github.com/nokia/danm; git pull --ff-only
fatal: unable to access 'https://github.com/nokia/danm/': Failed to connect to 10.158.100.6 port 8080: Connection timed out
package github.com/nokia/danm/pkg/crd/client/clientset/versioned: exit status 1
package github.com/nokia/danm/pkg/crd/client/informers/externalversions: cannot find package "github.com/nokia/danm/pkg/crd/client/informers/externalversions" in any of:
	/usr/lib/golang/src/github.com/nokia/danm/pkg/crd/client/informers/externalversions (from $GOROOT)
	/home/anannaya/data/STUDIES/PROGRAMMING/Go_programs/go/src/github.com/nokia/danm/pkg/crd/client/informers/externalversions (from $GOPATH)

**Comment by TothFerenc** [comment]
It is most likely a proxy issue in your environment.

**Comment by anannaya** [comment]
@TothFerenc  : Nope.
github.com/nokia/danm/pkg/crd/client/clientset/versioned
github.com/nokia/danm/pkg/crd/client/informers/externalversions

These 2 packages are not present.

**Comment by Levovar** [comment]
because they are generated
use the -d during go get, and use the build_danm script to build the binaries
also refer to discussion here: https://github.com/nokia/danm/issues/47

**Comment by anannaya** [comment]
Thanks,
