### ISSUE TITLE
Danm kubeconfig RBAC template

### ISSUE THREAD

**Issue by infinitydon** [nokia/danm#93]
Hi,

Can someone provide a sample kubeconfig file for the danm user with the necessary RBAC parameters (this will be referenced in the **00-danm.conf** as stated in the doc?

This was not clearly stated in the docs (unless am missing something)..

**Comment by Levovar** [comment]
You can find one in this comment:
https://github.com/nokia/danm/pull/45#discussion_r256840565

But you are right, this should be definitely in the repo.
I will add this example and the required RBAC setting in a jiffy!

**Comment by Levovar** [comment]
Here it is:
https://github.com/nokia/danm/commit/0614dcd9b33e0ab82abb4be6d1bc97fbd5be4912

**Comment by infinitydon** [comment]
Thanks!

**Comment by Levovar** [comment]
Also note that currently you shouldn't try to install from master. We are in the middle of refactoring DANM into a new major version.

Make sure to install the 3.3.0 release!

**Comment by infinitydon** [comment]
Ok.. I think it will be great to see some kind of roadmap information..

**Comment by Levovar** [comment]
> Ok.. I think it will be great to see some kind of roadmap information..

fair criticism :) I haven't pushed an exact timetable for the new major version, because there are a lots of things I'm figuring out as I do the changes

but we should definitely revisit this topic once the new version is released, and put together at least a list of stuff we want to do
